### ISSUE TITLE
ogbn-papers100m/load_dataset.py    line 108 bug

### ISSUE THREAD

**Issue by usccolumbia** [THUDM/SCR#2]
labels = labels.squeeze()
==
UnboundLocalError: local variable 'labels' referenced before assignment

how to fix this?

**Comment by yf-he** [comment]
Hi, 
Thank you for pointing out a bug in our code.  Please load the dataset this way. 
`g, labels = dataset[0]`

If you have any other questions, please feel free to contact us.
